#############################################################################
###
### Scripts associated with 2013 EOCT SCIENCE: Physical Science and Biology
###
#############################################################################

### PHYSICAL_SCIENCE

PHYSICAL_SCIENCE_2013.config <- list(
	PHYSICAL_SCIENCE.2013 = list( #34
		sgp.content.areas=c('SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2011','2013'),
		sgp.grade.sequences=list(c('8','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=12),
	PHYSICAL_SCIENCE.2013 = list( #35
		sgp.content.areas=c('SCIENCE','SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2010','2011','2013'),
		sgp.grade.sequences=list(c('7','8','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=11),
	PHYSICAL_SCIENCE.2013 = list( #36
		sgp.content.areas=c('SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2012','2013'),
		sgp.grade.sequences=list(c('8','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=10),
	PHYSICAL_SCIENCE.2013 = list( #37
		sgp.content.areas=c('SCIENCE','SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2011','2012','2013'),
		sgp.grade.sequences=list(c('7','8','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=9),
	PHYSICAL_SCIENCE.2013 = list( #38
		sgp.content.areas=c('SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2012','2013'),
		sgp.grade.sequences=list(c('7','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=8),
	PHYSICAL_SCIENCE.2013 = list( #39
		sgp.content.areas=c('SCIENCE','SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2011','2012','2013'),
		sgp.grade.sequences=list(c('6','7','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=7),
	PHYSICAL_SCIENCE.2013 = list( #40
		sgp.content.areas=c('BIOLOGY','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2011','2013'),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=6),
	PHYSICAL_SCIENCE.2013 = list( #41
		sgp.content.areas=c('SCIENCE','BIOLOGY','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2010','2011','2013'),
		sgp.grade.sequences=list(c('8','EOCT','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=5),
	PHYSICAL_SCIENCE.2013 = list( #42
		sgp.content.areas=c('BIOLOGY','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2012','2013'),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=4),
	PHYSICAL_SCIENCE.2013 = list( #43
		sgp.content.areas=c('SCIENCE','BIOLOGY','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2011','2012','2013'),
		sgp.grade.sequences=list(c('8','EOCT','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3),
	PHYSICAL_SCIENCE.2013 = list( #44
		sgp.content.areas=c('PHYSICAL_SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2012','2013'),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),
	PHYSICAL_SCIENCE.2013 = list( #45
		sgp.content.areas=c('PHYSICAL_SCIENCE','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2013','2013'),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.panel.years.within=c('FIRST_OBSERVATION', c('LAST_OBSERVATION')),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	PHYSICAL_SCIENCE.2013 = list( #46
		sgp.content.areas=c('BIOLOGY','PHYSICAL_SCIENCE'),
		sgp.panel.years=c('2013','2013'),
		sgp.grade.sequences=list(c('EOCT','EOCT')),
		sgp.panel.years.within=c('FIRST_OBSERVATION', 'LAST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=0)
) ### END PHYSICAL_SCIENCE_2013.config


### BIOLOGY

BIOLOGY_2013.config <- list(
	BIOLOGY.2013 = list( #47
		sgp.content.areas=c('SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2011', '2013'),
		sgp.grade.sequences=list(c('8', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=11),
	BIOLOGY.2013 = list( #48
		sgp.content.areas=c('SCIENCE', 'SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2010', '2011', '2013'),
		sgp.grade.sequences=list(c('7', '8', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=10),
	BIOLOGY.2013 = list( #49
		sgp.content.areas=c('SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2012', '2013'),
		sgp.grade.sequences=list(c('8', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=9),
	BIOLOGY.2013 = list( #50
		sgp.content.areas=c('SCIENCE', 'SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2011', '2012', '2013'),
		sgp.grade.sequences=list(c('7', '8', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=8),
	BIOLOGY.2013 = list( #51
		sgp.content.areas=c('PHYSICAL_SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2011', '2013'),
		sgp.grade.sequences=list(c('EOCT', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=7),
	BIOLOGY.2013 = list( #52
		sgp.content.areas=c('SCIENCE', 'PHYSICAL_SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2010', '2011', '2013'),
		sgp.grade.sequences=list(c('8', 'EOCT', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=6),
	BIOLOGY.2013 = list( #53
		sgp.content.areas=c('PHYSICAL_SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2012', '2013'),
		sgp.grade.sequences=list(c('EOCT', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=5), 
	BIOLOGY.2013 = list( #54
		sgp.content.areas=c('SCIENCE', 'PHYSICAL_SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2011', '2012', '2013'),
		sgp.grade.sequences=list(c('8', 'EOCT', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=4), 
	BIOLOGY.2013 = list( #55
		sgp.content.areas=c('SCIENCE', 'PHYSICAL_SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2011', '2012', '2013'),
		sgp.grade.sequences=list(c('7', 'EOCT', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=3), 
	BIOLOGY.2013 = list( #56
		sgp.content.areas=c('BIOLOGY', 'BIOLOGY'),
		sgp.panel.years=c('2012', '2013'),
		sgp.grade.sequences=list(c('EOCT', 'EOCT')),
		sgp.panel.years.within=c('LAST_OBSERVATION', 'FIRST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=2),
	BIOLOGY.2013 = list( #57
		sgp.content.areas=c('BIOLOGY', 'BIOLOGY'),
		sgp.panel.years=c('2013', '2013'),
		sgp.grade.sequences=list(c('EOCT', 'EOCT')),
		sgp.panel.years.within=c('FIRST_OBSERVATION', 'LAST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=1),
	BIOLOGY.2013 = list( #58
		sgp.content.areas=c('PHYSICAL_SCIENCE', 'BIOLOGY'),
		sgp.panel.years=c('2013', '2013'),
		sgp.grade.sequences=list(c('EOCT', 'EOCT')),
		sgp.panel.years.within=c('FIRST_OBSERVATION', 'LAST_OBSERVATION'),
		sgp.exact.grade.progression=TRUE,
		sgp.norm.group.preference=0)
) ### END BIOLOGY_2013.config
